#!/usr/bin/env bash
# Only use ssh single-character flags
# You cannot use -l
# You do not need to handle the case of a private key protected by a passphrase
ssh ubuntu@34.207.63.227 -i ~/.ssh/school
